pkg/package-format/appimage/templates/AppRun.sh
pkg/package-format/bindata.go

Wherever mktemp is invoked, it seems to take 6 characters from project name, prefix it with `.mount_` and suffix with a few random characters. If there is a space in those first 6 characters (for example the project may be called “Abc Blahblah”), the `[ -z $APPDIR ]` test fails with something like “unexpected operator” (the test may look like `[ -z Abc Blahblah ]`).

fix: APPDIR (in AppRun.sh template) may contain spaces

---

pkg/package-format/fpm/fpm.go

Even though electron-builder supports setting compression for pacman targets, app-builder doesn't pass it along to fpm. This should fix that.

Support pacman compression arguments

---

pkg/download/tool.go
pkg/linuxTools/tool.go
pkg/package-format/snap/snap.go
pkg/wine/wine.go

Added function to get the base URL for GitHub (electron-builder-binaries) using environment variables used by electron-builder (https://github.com/electron-userland/electron-builder/blob/f3404d32f029dfb63e83067012f15ef67838f326/packages/app-builder-lib/src/binDownload.ts#L21-L25).
This could also be extended in a similar way for "ELECTRON_BUILDER_BINARIES_CUSTOM_DIR".
The implantation is not tested, however it is structured the same way as https://github.com/develar/app-builder/blob/7e03397c8b546e001217ab3cac41900fab189bf9/pkg/electron/electronDownloader.go#L84-L99 and should work without any problems.

feat: electron builder binaries base url from env

---

pkg/rcedit/rcedit.go
pkg/util/wsl.go

Hello,
Thank you for making this package!
I tried to use it on `WSL` (Windows Subsystem for Linux).
`WSL` is a Linux specially built for running seemlessly.
It could not use `wine` due to kernel differences but it can call Win32 executables (`.exe`) directly.
I make an improvement to your lib to detect `WSL` and call `rcedit.exe` directly rather than using `wine`.
*Note: I'm also working on a `electron-builder` PR to add `WSL` support. This PR will require this change on `app-builder`*
Thanks

Add WSL (Windows Subsystem for Linux) support

---

pkg/package-format/fpm/fpm.go

Arch Linux no longer distributes the "obsoleted" libappindicator-sharp
package.
https://lists.archlinux.org/pipermail/arch-commits/2020-March/722392.html

fix(linux): remove libappindicator-sharp from pacman dependency list

---

pkg/download/downloader.go

This allows you to set a custom CA root for downloads, e.g. for transparent caching of downloads via a proxy.
```
env HTTP_PROXY=http://localhost:8080 HTTPS_PROXY=http://localhost:8080 NODE_EXTRA_CA_CERTS=~/.mitmproxy/mitmproxy-ca-cert.pem ./app-builder download --url="https://github.com/facebook/flipper/releases/download/v0.34.0/Flipper-mac.dmg" --output="/tmp/download"
```
I saw that this tries to reuse as much from npm/node as possible to make the integration with electron-builder etc. very convenient. I'm not sure if there's a more app-builder-specific env var as an alternative to that should be accepted here?
Is there any place where the env vars are currently documented and this should be mentioned?

Ability to add custom CA roots for downloads via env var

---

pkg/plist/plist.go

In binary you can't sign and notarizing for publish in App Store

Binary plist to XMLFormat

---

pkg/package-format/snap/snap.go

Snapcraft has ignored the target-arch flag, which works in very
limited circumstances, with destructive mode.  Snapcraft considers
it unsupported and will not be fixed in its current form.
Recently snapcraft regarded improper usage of this as a hard error
instead of silently ignoring, which broke users of app-builder. We
reverted that to simply warn, but this fix is to remove its usage
from app-builder.
If the user is targeting an arch that is not the host arch,
error out with a nice message.
However, it does require that --arch with `snap` must use the
scheme provided by go. If there are a set of supported architecture
options somewhere, I can update to ensure that they map to GOARCH.
Closes: #40
Signed-off-by: Chris Patterson <chris.patterson@canonical.com>

fix(snap): remove incorrect usage of --target-arch for snapcraft

---

pkg/node-modules/rebuild.go

This is a follow-up on #44 (that was landed surprisingly fast 😅 ) that adds a bit more verbose and descriptive error logging when something goes wrong during javascript file detection.

Proper error handling & fixing a minor bug when parsing hashbang

---

pkg/node-modules/nodeModuleCollector.go
pkg/node-modules/rebuild.go
pkg/node-modules/tree.go

fixes #46 
Before:
```
julus@julus-thinkpad:~/Projects/companion-build/test$ yarn electron-builder install-app-deps --platform win32
yarn run v1.22.5
$ /home/julus/Projects/companion-build/test/node_modules/.bin/electron-builder install-app-deps --platform win32
• electron-builder  version=22.9.1
• rebuilding native dependencies  dependencies=node-hid@2.1.1 platform=win32 arch=x64
• install prebuilt binary  name=node-hid version=2.1.1 platform=win32 arch=x64
⨯ cannot build native dependency  reason=prebuild-install failed with error and build from sources not possible because platform or arch not compatible
cause=exit status 1
errorOut=prebuild-install info begin Prebuild-install version 6.0.0
prebuild-install info looking for cached prebuild @ …
```

fix: instruct prebuild-install to download napi builds

---

app-builder-bin/index.js

Currently, running `electron-builder` on Windows ARM64 leads to the following error:
```
• electron-builder  version=22.9.1
• loaded configuration  file=package.json ("build" field)
⨯ spawn C:\repos\Signal-Desktop\node_modules\app-builder-bin\win\arm64\app-builder.exe ENOENT  stackTrace=
Error: spawn C:\repos\Signal-Desktop\node_modules\app-builder-bin\win\arm64\app-builder.exe ENOENT
at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
at onErrorNT (internal/child_process.js:465:16)
at processTicksAndRejections (internal/process/task_queues.js:80:21)
```
This is because there's no binary for Windows ARM64 yet. This PR works around that.
**Some background**
Golang isn't available for Windows ARM64 yet, so an ARM64 binary can't be built yet. However, Windows ARM64 does …

Use 32-bit (ia32) app-builder.exe on Windows ARM64

---

pkg/package-format/snap/desktop-scripts/desktop-common.sh

When a user has one or several `XDG_SPECIAL_DIRS` folders symlinked in
their real home folder to elsewhere in their real home folder
`desktop-common.sh` will attempt to mv those folders to themselves.
Because we are executing this script with `bash -e`, this prevents any
Snap with the `home` interface built with these scripts from launching
when the user has moved any of their Documents, Pictures, Music, etc.
and replaced with a symlink.
* guard `mv` calls with test for `is_subpath` to ensure that we're only
moving symlinks we created.
See related PRs on Snapcraft-desktop-helpers and Snapcraft:
* ubuntu/snapcraft-desktop-helpers#220
* snapcore/snapcraft#3435
Signed-off-by: Daniel Llewellyn <diddledan@ubuntu.com>

fix: Snaps fail when user has symlinked XDG_SPECIAL_DIRS in HOME

---

.gitignore
Makefile
app-builder-bin/index.js
scripts/build.sh

Configures the build so that it can produce executables for darwin arm64, AKA "M1" Macs.
Because Go can't yet build universal binaries alone, and the Apple supplied tool to build universal binaries is unavailable on non-Darwin platforms, we simply build and distribute versions of the executable for both architectures, and select the appropriate one at runtime in Javascript. For backwards compatibility, an `app-builder` symlink to the amd64 executable is maintained.
Resolves issue #56.

Add support for darwin arm64

---

pkg/package-format/snap/snap.go

Fixes https://github.com/develar/app-builder/issues/64
Some reading about the motivation behind LZO compression for snaps https://snapcraft.io/blog/snap-speed-improvements-with-new-compression-algorithm

Optionally support LZO compression for snap

---

pkg/node-modules/rebuild.go

Would fix #63.
Because pnpm uses the hashbang `/usr/bin/env node`, only checking until the first space as is current done will miss the `node`.
This change will only include the space if the text before the space is "/usr/bin/env", so that it doesn't break any existing code (`/usr/bin/env` would fail the check anyway)
This fix is working in my [minimum reproduction of the issue](https://github.com/Alduino/app-builder-navw32a-repro/runs/3534414708) (the Test stage)
Running it in the original repository that I found the bug in, it is getting past where it got before (it doesn't get the %1 is not a valid command error) but now at the end of the postinstall it [gets another error](https://github.com/Alduino/Muzik/runs/3534341190) (Install & Build stage):
```
apps/desktop postinstall: 'li.js" …
```

Check whole hashbang line if it is /usr/bin/env

---

pkg/package-format/appimage/appImage.go

See: https://github.com/electron-userland/electron-builder/issues/6678
```
• electron-builder  version=23.0.1 os=5.15.25-1-lts
• loaded configuration  file=/home/mscharley/Code/mscharley/notes-nc/electron-builder.yml
• writing effective config  file=dist/builder-effective-config.yaml
• packaging       platform=linux arch=x64 electron=17.1.0 appOutDir=dist/linux-unpacked
• building        target=AppImage arch=x64 file=dist/notes-nc-0.3.0.AppImage
• default Electron icon is used  reason=application icon is not set
⨯ enum value must be one of xz,gzip, got 'zlib'
```
```
⨯ enum value must be one of xz,gzip, got 'lzo'
⨯ /home/mscharley/Code/mscharley/notes-nc/node_modules/app-builder-bin/linux/x64/app-builder process failed ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
```
```
$ electron-builder …
```

fix: incorrect enums for updated appimage-13 mksquashfs compressors

---

pkg/node-modules/tree.go

Before:
```
{"name":"zstd-napi","version":"0.0.6","hasPrebuildInstall":true,"napiVersions":[35]}
```
After:
```
{"name":"zstd-napi","version":"0.0.6","hasPrebuildInstall":true,"napiVersions":[3,5]}
```

fix(node-modules): incorrect generation of napi_versions

---

Makefile
app-builder-bin/index.js
scripts/build.sh

Go supports Windows ARM64 since Go 1.17, so it's not possible to create native builds for `app-builder-bin`.

Add Windows ARM64 support

---

pkg/package-format/snap/snap.go
pkg/package-format/snap/snapStore.go
pkg/package-format/snap/snap_test.go

Addresses the [deprecation warning](http://snapcraft.io/docs/deprecation-notices/dn11):
```
DEPRECATED: The 'push' set of commands have been replaced with 'upload'.
See http://snapcraft.io/docs/deprecation-notices/dn11 for more information.
```
Requires the use of Snapcraft 4.0.

Use snapcraft upload instead of push

---

.changeset/gorgeous-rabbits-sell.md
index.js
package.json

Allow providing env var for custom app-builder binary as opposed to accessing directly from the PATH env var

feat: add `CUSTOM_APP_BUILDER_PATH` for testing purposes instead of searching `PATH`

---

.changeset/real-clocks-cheer.md
pkg/linuxTools/tool.go

Fixes: https://github.com/electron-userland/electron-builder/pull/7774#issuecomment-2002183219

fix: revert appimage 13.0.1 to 13.0.0 due to miscompiled arch artifacts

---

.changeset/tasty-houses-drum.md
pkg/node-modules/nodeModuleCollector.go

fix: hoist dependencies to the real parent

---

.changeset/serious-lizards-invite.md
pkg/package-format/appimage/appImage.go

Current mksquashfs only allows xz and gzip compression options

fix: use correct compression args as mksquashfs

---

.changeset/strange-parrots-smoke.md
pkg/package-format/appimage/appImage.go

Resolves: https://github.com/electron-userland/electron-builder/actions/runs/9996522006/job/27631089267?pr=8353
```
• building        target=AppImage arch=x64 file=/tmp/et-db411cd21f3bbd882f3a5a30c58db6ff/t-EHDsQx/test-project-2/dist/Test App ßW-1.1.0.AppImage
⨯ cannot execute  cause=exit status 1
errorOut=/root/.cache/electron-builder/appimage/appimage-13.0.0/linux-x64/mksquashfs: Compressor "gzip" is not supported!
/root/.cache/electron-builder/appimage/appimage-13.0.0/linux-x64/mksquashfs: Compressors available:
lzo
xz
zstd (default)
```

fix(appimage): remove default and fix compression options

---

.changeset/early-dots-repair.md
pkg/linuxTools/tool.go

fix: to resolve appimage issues in electron builder, and since we can't update electron-builder-binaries repo, we should just downgrade to the last working version of appimage

fix: downgrade appimage 13.0.0->12.0.1

---

.changeset/mean-dodos-smoke.md
pkg/fs/findParent.go
pkg/node-modules/nodeModuleCollector.go

fix https://github.com/electron-userland/electron-builder/issues/8426
package.json
```
{
"name": "npm-demo",
"version": "1.0.0",
"description": "",
"main": "index.js",
"scripts": {
"test": "echo \"Error: no test specified\" && exit 1"
},
"keywords": [],
"author": "",
"license": "ISC",
"dependencies": {
"parse-asn1":"5.1.7"
}
}
```
```
../../../app-builder  node-dep-tree --flatten --dir ~/Code/app-builder/pkg/node-modules/npm-demo
⨯ stat /root/Code/app-builder/pkg/node-modules/npm-demo/node_modules/parse-asn1/asn1.js/package.json: not a directory
github.com/develar/app-builder/pkg/node-modules.(*Collector).resolveDependency
/root/Code/app-builder/pkg/node-modules/nodeModuleCollector.go:236
github.com/develar/app-builder/pkg/node-modules.(*Collector).processDependencies …
```

fix: find the real parent node module

---

.changeset/old-monkeys-drum.md
pkg/package-format/fpm/fpm.go

OpenSUSE does not provide libXtst and libuuid packages, but does provide libXtst6 and libuuid1.
This PR changes the default dependencies in a way that both variants of the pacakge names are supported.

feat: Support Package Creation for OpenSUSE

---

.changeset/strange-pianos-move.md
pkg/download/artifactDownloader.go

Conditionally adds `-snld` flag based on detecting SZA binary path to have suffix `7za`.
Maintains backward compatibility of app-builder-bin's extract artifact logic between versions of 7za (old) and 7zz/7zzs/7zr.exe (new)
Ref: https://sourceforge.net/p/sevenzip/bugs/2356/
Tested with artifacts in related PR https://github.com/develar/7zip-bin/pull/27

chore: Update extract logic for using newer 7zz/7zzs/7zr.exe binaries

---

.changeset/unlucky-brooms-melt.md
pkg/node-modules/nodeModuleCollector.go
pkg/node-modules/nodeModuleCollector_test.go
pkg/node-modules/tar-demo/package-lock.json
pkg/node-modules/tar-demo/package.json

fix https://github.com/electron-userland/electron-builder/issues/8503
Using strings.HasPrefix for direct comparison is problematic. For example, with "archiver" and "archiver-utils", their paths are "node_modules/archiver" and "node_modules/archiver-utils" respectively. They are not in a parent-child path relationship. This incorrect assessment resulted in archiver-utils not being placed at the top.

fix: cannot find module(archiver-utils)

---

.changeset/healthy-flies-rescue.md
pkg/publisher/s3.go

close https://github.com/develar/app-builder/issues/145
Downstream Issue: https://github.com/electron-userland/electron-builder/issues/8674

feat: add s3ForcePathStyle option for s3 publisher

---

.changeset/soft-doors-play.md
pkg/download/tool.go

Current logic already uses env var `ELECTRON_BUILDER_BINARIES_MIRROR`
https://github.com/develar/app-builder/blob/580c34f2e19347061bc2243fa6ab6e57e9bbd2a6/pkg/download/tool.go#L61-L81
But it does not allow customization of the dir (both being the `id` of the asset)
https://github.com/develar/app-builder/blob/580c34f2e19347061bc2243fa6ab6e57e9bbd2a6/pkg/download/tool.go#L63
This implementation now will properly mirror the (duplicated) logic in electron-builder for app-builder-bin downloading
https://github.com/electron-userland/electron-builder/blob/3d65267a6c53ca824f70e5b0f5d8f4ba8be38237/packages/app-builder-lib/src/binDownload.ts#L25-L38

feat: adding env var for "dirname" to mirror the logic in electron-builder

---

.changeset/curly-parents-peel.md
pkg/icons/icns.go

All ICNS resource type entries are made of a type and a length. The resource type is always a 4 byte string - if it's shorter than 4 bytes, it is filled with space (0x20) characters. This is also the case for the 'TOC ' resource type, so add the missing space character.

fix: handle the table of content resource type correctly
